# Generated by Django 5.1.5 on 2025-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
