# Generated by Django 5.1.5 on 2025-02-04 15:04

from django.db import migrations, models
import django.contrib.auth.models

class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='seller',
            field=models.ForeignKey(default=1, to=django.contrib.auth.models.User, on_delete=models.CASCADE),
            preserve_default=False,
        )
    ]
