# Generated by Django 5.1.5 on 2025-02-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0003_remove_venue_location_remove_venue_photo_venue_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='amenities_price',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='venue',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='extra_guest_price',
            field=models.IntegerField(default=0),
        ),
    ]
