# Generated by Django 5.1.5 on 2025-02-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0005_pricingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingrequest',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wedding.venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='venue',
            name='availability',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(db_index=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, default='default_venue.jpg', null=True, upload_to='venue_images/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
