# Generated by Django 5.1.5 on 2025-02-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0006_pricingrequest_status_alter_pricingrequest_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(null=True),
        ),
    ]
