# Generated by Django 5.1.5 on 2025-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0008_alter_venue_amenities_alter_venue_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='availability',
            field=models.JSONField(default=list),
        ),
    ]
