# Generated by Django 5.1.5 on 2025-02-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0013_servicelisting_description_servicelisting_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicelisting',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='servicelisting',
            name='amenities',
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='amenities_price',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='extra_guest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
