# Generated by Django 5.1.5 on 2025-02-18 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0014_rename_price_servicelisting_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerearnings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
