# Generated by Django 5.1.5 on 2025-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0015_sellerearnings_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingrequest',
            name='venue',
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='seller_email',
            field=models.EmailField(default='irachand620@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pricingrequest',
            name='service_name',
            field=models.CharField(default='Venue', max_length=200),
            preserve_default=False,
        ),
    ]
