# Generated by Django 5.1.5 on 2025-02-25 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0018_event_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='rsvp_status',
        ),
        migrations.AddField(
            model_name='guest',
            name='assigned_side',
            field=models.CharField(choices=[('Bride', 'Bride'), ('Groom', 'Groom')], default='Bride', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='category',
            field=models.CharField(choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Colleagues', 'Colleagues'), ('VIP', 'VIP')], default='Friends', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Wedding.guest')),
            ],
        ),
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Gluten-Free', 'Gluten-Free')], default='Veg', max_length=20)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Wedding.guest')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Attending', 'Attending'), ('Not Attending', 'Not Attending'), ('Maybe', 'Maybe')], default='Maybe', max_length=15)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Wedding.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wedding.guest')),
            ],
        ),
    ]
