# Generated by Django 5.1.5 on 2025-02-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0020_remove_guest_event_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
